replicaCount: 1

rabbitmq:
  host: rabbitmq.default.svc.cluster.local
  port: 5672
  user: myuser
  password: mypassword

producer:
  image:
    repository: nogayehudai/producer
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  serviceAccount:
    create: true
    name: "producer-sa"
  message: "Hello from Producer"   # Add message to send
  runs: 5                          # Add the number of runs

consumer:
  image:
    repository: nogayehudai/consumer
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8081
  serviceAccount:
    create: true
    name: "consumer-sa"




