# templates/service.yaml

# Producer Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-producer
  labels:
    app: producer
spec:
  type: {{ .Values.producer.service.type }}
  ports:
    - port: {{ .Values.producer.service.port }}
      targetPort: {{ .Values.producer.service.targetPort }}
  selector:
    app: {{ .Release.Name}}-producer

---

# Consumer Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-consumer
  labels:
    app: {{ .Release.Name}}-consumer
spec:
  type: {{ .Values.consumer.service.type }}
  ports:
    - port: {{ .Values.consumer.service.port }}
      targetPort: {{ .Values.consumer.service.targetPort }}
  selector:
    app: {{ .Release.Name}}-consumer
