# templates/serviceaccount.yaml

# Producer ServiceAccount
{{- if .Values.producer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.producer.serviceAccount.name }}
{{- end }}

---

# Consumer ServiceAccount
{{- if .Values.consumer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.consumer.serviceAccount.name }}
{{- end }}
